# Generated by Django 2.0.5 on 2018-11-05 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shopping_cart', '0002_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dilivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('town', models.CharField(max_length=150)),
                ('zipcode', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('dilivery', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile')),
            ],
        ),
    ]
