# Generated by Django 2.0.5 on 2018-11-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shopping_cart', '0003_dilivery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dilivery',
            new_name='Delivery',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='dilivery',
            new_name='delivery',
        ),
    ]
