# Generated by Django 2.0.5 on 2018-10-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20181021_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(to='products.Tags'),
        ),
    ]
