# Generated by Django 2.0.5 on 2018-10-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_tags_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(to='products.SubCategorie'),
        ),
    ]
