# Generated by Django 2.0.5 on 2018-10-22 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20181022_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
