# Generated by Django 2.0.5 on 2018-10-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20181022_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorie',
            name='slug',
        ),
    ]
