# Generated by Django 2.0.5 on 2018-10-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_subcategorie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='celebrity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='inspiredOutfit',
            field=models.BooleanField(default=False),
        ),
    ]
