# Generated by Django 2.0.5 on 2018-11-01 12:21

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20181023_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('insta', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=products.models.upload_image_path)),
            ],
        ),
    ]
