# Generated by Django 2.0.5 on 2019-01-11 07:35

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20181104_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='bannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
            ],
        ),
    ]
